### ISSUE TITLE
Wagtail 3.0 - 4.1 upgrade

### ISSUE THREAD

**Issue by katdom13** [torchbox-forks/wagtail-django-recaptcha#4]
PR: https://github.com/springload/wagtail-django-recaptcha/pull/44

**Important:**

It's important that this be merged and released first before https://github.com/springload/wagtail-django-recaptcha/pull/45 so projects using older versions of Wagtail can use that release.

**Comment by zerolab** [comment]
Fixed by #1 or #2 ?

**Comment by katdom13** [comment]
@zerolab ,
Think this is fixed by: https://github.com/torchbox-forks/wagtail-django-recaptcha/pull/2
Closing this now.
Thanks!
